image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


pod:
  resources: {}


service:
  type: "LoadBalancer"
  port: 5432


postgresql:
  user: postgresql
  database: postgresql
  passwordSecretKey: POSTGRES_PASSWORD


externalResources:
  envSecretName: ""
  volumeClaimName: ""