
image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

pods:
  homeassistant:
    resources: {}

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: false
  hosts:
    - host: homeassistant.local
      path:
        path: /
        pathType: ImplementationSpecific
  tls: []

github:
  ssh_key: ""

volumeClaimName: ""

postgresql:
  postgres:
    user: homeassistant
    database: homeassistant
