# Default values for homeassistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: homeassistant.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}