image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

pod:
  resources: {}

service:
  type: ClusterIP
  port: 8123

ingress:
  enabled: false

  hosts:
    - host: homeassistant.local
      path:
        path: /
        pathType: ImplementationSpecific
  
  tls: []

externalResources:
  volumeClaimName: ""

postgresql:
  image:
    tag: "15.3"

  pod:
    resources: {}

  postgresql:
    user: homeassistant
    database: homeassistant
  
  externalResources:
    envSecretName: ""
    volumeClaimName: ""

mosquitto:
  image:
    tag: "2.0.15"

  externalResources:
    configMapName: ""
