container:
  image: homeassistant/home-assistant
  tag: ""

persistantVolumeClaim:
  create: false

service:
  create: true
  type: ClusterIP
  port: 8123

ingress:
  create: true

  hosts: []
  tls: []

certificate:
  enabled: false

externalResources:
  persistantVolumeClaimName: ""
