image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

pods:
  postgres:
    resources: {}

service:
  type: "LoadBalancer"
  port: 1883

externalResources:
  configMapName: ""