{{- define "deployment.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ printf "%s-%s" .Release.Name "postgres" }}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "deployment.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaimName | required "Value volumeClaimName is required" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPoint: /var/lib/postgreql/data
              name: postgresql
              subPath: database
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | required "Value postgres.password is required." }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database }}
          resources: {{ toYaml .Values.pods.postgres.resources | nindent 12 }}
