apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      hostname: {{ .Release.Name }}
      volumes:
        - name: homeassistant
          persistentVolumeClaim: 
            claimName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          securityContext:
            runAsUser: {{ .Values.deployment.runAsUser }}
            runAsGroup: {{ .Values.deployment.runAsGroup }}
          ports:
            - name: http
              containerPort: 8123
          volumeMounts:
            - name: homeassistant
              mountPath: /config
              subPath: config