apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.basename" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "deployment.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: homeassistant
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaimName | required "Value volumeClaimName is required" }}
        - name: ssh
          secret:
            secret_name: {{ .values.sshSecretName | required "Value sshSecretName is required" }}
      containers:
        - name: homeassistant
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: homeassistant
              subPath: config
          resources: {{ toYaml .Values.pods.homeassistant.resources | nindent 12 }}