apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: homeassistant.alexander.coleslab.com
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
            pathType: Prefix
            path: '/'
  # tls:
  #   - hosts: 
  #       - homeassistant.alexander.coleslab.com
  #     secretName: {{ .Release.Name }}-tls