apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{.Release.Namespace}}
spec:
  resources:
    requests:
      storage: 5Gi
  {{ if .Values.storage.storageClass }}
  storageClassName: {{.Values.storage.storageClass}}
  {{ end }}
  accessModes:
    - ReadWriteOnce