apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      {{ toYaml .Values.volumes.config.requests | nindent 6 }}
  accessModes:
    - ReadWriteOnce