apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.basename" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  resources:
    requests: {{ toYaml .Values.volumeClaim.requests | nindent 6 }}
  accessModes:
    - ReadWriteOnce
  {{- if and .Values.volumeClaim.volumeName .Values.volumeClaim.storageClassName -}}
  {{ fail "Only one of .Values.volume.volumeName or .Values.volume.storageClassName can be set" }}
  {{- end -}}
  {{- if .Values.volumeClaim.volumeName}}
  volumeName: {{ .Values.volumeClaim.volumeName}}
  {{- end}}
  {{- if .Values.volumeClaim.storageClassName}}
  storageClassName: {{ .Values.volumeClaim.storageClassName }}
  {{- end}}