image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

pods:
  postgres:
    resources: {}

service:
  type: "LoadBalancer"
  port: 5432

postgres:
  user: postgres
  password: ""
  database: postgres

volumeClaimName: ""