apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "deployment.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: {{ .Values.externalResources.volumeClaimName | required "Value externalResources.volumeClaimName is required" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgreql/data
              name: postgresql
              subPath: database
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalResources.envSecretName | required "Value externalResources.envSecretName is required" }}
                  key: {{ .Values.postgresql.passwordSecretKey }}
                  optional: false
          resources: {{ toYaml .resources | nindent 12 }}
