apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector: {{- include "deployment.selectorLabels" . | nindent 4 -}}
