{{- define "deployment.selectorLabels" -}}
app.kubernetes.io/name: {{ .Chart.Name }}
app.kubernetes.io/instance: {{ printf "%s-%s" .Release.Name "postgres" }}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels: {{ include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "deployment.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "deployment.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: mosquitto
          persistentVolumeClaim:
            claimName: {{ .Values.volumeClaimName | required "Value volumeClaimName is required" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mosquitto
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto
              subPath: config
          resources: {{ toYaml .Values.pods.postgres.resources | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: alpine
          volumeMounts:
            - mountPath: /mosquitto/config
              name: mosquitto
              subPath: config
          env:
            - name: MOSQUITTO_USER
              value: {{ .Values.mqtt.user }}
            - name: MOSQUITTO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mqtt.passwordSecretName | required "Value mqtt.passwordSecretName is required" }}
                  key: {{ .Values.mqtt.passwordSecretKey | required "Value mqtt.passwordSecretKey is required" }}
          command: ["/bin/sh"]
          args: ["-c", "
            echo "" > /mosquitto/config/mosquitto.conf
            exit 1
          "]
          

